const ResponseMessage = {
    VERIFY_SUCCESS: "verify-success",
    VERIFY_FAILED: "verify-failed",
    CREATE_SUCCESS: "create-success",
    CREATE_FAILED: "create-failed",
    GET_SUCCESS: "get-success",
    GET_FAILED: "get-failed",
    UPDATE_SUCCESS: "update-success",
    UPDATE_FAILED: "update-failed",
    DELETE_SUCCESS: "delete-success",
    DELETE_FAILED: "delete-failed",
    REGISTER_SUCCESS: "register-success",
    REGISTER_FAILED: "register-failed",
    LOGIN_SUCCESS: "login-success",
    LOGIN_FAILED: "login-failed",
    REFRESH_TOKEN_SUCCESS: "refresh-token-success",
    LOGOUT_SUCCESS: "logout-success",
    LOGOUT_FAILED: "logout-failed",
    SEND_OTP_SUCCESS: "send-otp-success",
    WRONG_OTP: "wrong-otp",
    ACCESS_TOKEN_NOT_FOUND: "access-token-not-found",
    INVALID_TOKEN: "invalid-token",
    WRONG_ACCOUNT_OR_PASSWORD: "wrong-account-or-password",
    ACCOUNT_INACTIVE: "account-inactive",
    REFRESH_TOKEN_NOT_FOUND: "refresh-token-not-found",
    INVALID_REFRESH_TOKEN: "invalid-refresh-token",
    REFRESH_TOKEN_FAILED: "refresh-token-failed",
    USER_NOT_FOUND: "user-not-found",
    SEND_OTP_FAILED: "send-otp-failed",
    TITLE_REQUIRED: "title-required",
    FILE_REQUIRED: "file-required",
    EMAIL_EXISTED: "email-existed",
    PASSWORD_NOT_MATCH: "password-not-match",
    FIELD_REQUIRED: "field-required",
};

export default ResponseMessage;