INSERT INTO topic (name, hexa_color, deleted, createdAt, updatedAt) VALUES
('Thiên nhiên', '#00FF00', FALSE, NOW(), NOW()),
('Công nghệ', '#0000FF', FALSE, NOW(), NOW()),
('Du lịch', '#FF4500', FALSE, NOW(), NOW()),
('Ẩm thực', '#FFD700', FALSE, NOW(), NOW()),
('Nghệ thuật', '#FF1493', FALSE, NOW(), NOW()),
('Thời trang', '#800080', FALSE, NOW(), NOW()),
('Âm nhạc', '#8A2BE2', FALSE, NOW(), NOW()),
('Thể thao', '#008000', FALSE, NOW(), NOW()),
('Sức khỏe', '#FF6347', FALSE, NOW(), NOW()),
('Phim ảnh', '#696969', FALSE, NOW(), NOW()),
('Động vật', '#DA70D6', FALSE, NOW(), NOW()),
('Nhiếp ảnh', '#FF69B4', FALSE, NOW(), NOW()),
('Lịch sử', '#A52A2A', FALSE, NOW(), NOW()),
('Khoa học', '#7FFF00', FALSE, NOW(), NOW()),
('Giáo dục', '#1E90FF', FALSE, NOW(), NOW()),
('Chính trị', '#FF4500', FALSE, NOW(), NOW()),
('Kinh tế', '#2E8B57', FALSE, NOW(), NOW()),
('Môi trường', '#228B22', FALSE, NOW(), NOW()),
('Phong cách sống', '#FF8C00', FALSE, NOW(), NOW()),
('Trò chơi', '#483D8B', FALSE, NOW(), NOW()),
('Sách', '#8B4513', FALSE, NOW(), NOW()),
('Tự làm', '#808080', FALSE, NOW(), NOW()),
('Văn hóa', '#6A5ACD', FALSE, NOW(), NOW()),
('Vũ trụ', '#000080', FALSE, NOW(), NOW()),
('Kiến trúc', '#4682B4', FALSE, NOW(), NOW()),
('Ô tô', '#B22222', FALSE, NOW(), NOW()),
('Làm đẹp', '#FF69B4', FALSE, NOW(), NOW()),
('Hài kịch', '#FFD700', FALSE, NOW(), NOW()),
('Thú cưng', '#ADFF2F', FALSE, NOW(), NOW());