export const ResponseMessage = {
  REGISTER_SUCCESS: "register-success",
  REGISTER_FAILED: "register-failed",
  LOGIN_SUCCESS: "login-success",
  LOGIN_FAILED: "login-failed",
  REFRESH_TOKEN_SUCCESS: "refresh-token-success",
  LOGOUT_SUCCESS: "logout-success",
  LOGOUT_FAILED: "logout-failed",
  SEND_OTP_SUCCESS: "send-otp-success",
  WRONG_OTP: "wrong-otp",
  VERIFY_OTP_SUCCESS: "verify-otp-success",
  VERIFY_OTP_FAILED: "verify-otp-failed",
  CREATE_PIN_SUCCESS: "create-pin-success",
  CREATE_PIN_FAILED: "create-pin-failed",
  GET_PINS_SUCCESS: "get-pins-success",
  GET_PINS_FAILED: "get-pins-failed",
  GET_PINS_BY_TOPIC_SUCCESS: "get-pins-by-topic-success",
  GET_PINS_BY_TOPIC_FAILED: "get-pins-by-topic-failed",
  GET_ALL_TOPICS_SUCCESS: "get-all-topics-success",
  GET_ALL_TOPICS_FAILED: "get-all-topics-failed",
  GET_INFO_SUCCESS: "get-info-success",
  VERIFY_LOGIN_SUCCESS: "verify-success",
  ACCESS_TOKEN_NOT_FOUND: "access-token-not-found",
  INVALID_TOKEN: "invalid-token",
  WRONG_ACCOUNT_OR_PASSWORD: "wrong-account-or-password",
  ACCOUNT_INACTIVE: "account-inactive",
  REFRESH_TOKEN_NOT_FOUND: "refresh-token-not-found",
  INVALID_REFRESH_TOKEN: "invalid-refresh-token",
  REFRESH_TOKEN_FAILED: "refresh-token-failed",
  USER_NOT_FOUND: "user-not-found",
  SEND_OTP_FAILED: "send-otp-failed",
  TITLE_REQUIRED: "title-required",
  FILE_REQUIRED: "file-required",
  EMAIL_EXISTED: "email-existed",
  PASSWORD_NOT_MATCH: "password-not-match",
  FIELD_REQUIRED: "field-required",
};

export const HttpStatusCode = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  METHOD_NOT_ALLOWED: 405,
  INTERNAL_SERVER_ERROR: 500,
};
